### ISSUE TITLE
SDKs

### ISSUE THREAD

**Issue by BRAVO68WEB** [BRAVO68WEB/stockpile#5]
- Create Node SDK

**Comment by dannysheridan** [comment]
@BRAVO68WEB for the Node SDK, have you considered auto-generating it? 
Can check out our open source project at www.buildwithfern.com 
we take care of generating and publishing your SDKs.

**Comment by BRAVO68WEB** [comment]
Hmm, let me check that.

PS: looks good to me.

**Comment by BRAVO68WEB** [comment]
SDK release at [BRAVO68WEB/stockpile-node-sdk](https://github.com/BRAVO68WEB/stockpile-node-sdk/)
